# Application properties that need to be
# embedded within the web application can be included here

server:
  ssl:
    key-store: classpath:keystore
    key-store-password: changeit
    key-password: changeit

cas:
  authn:
    accept:
      enabled: true
      users: admin::123456
  service-registry:
    core:
      init-from-json: true
    json:
      location: classpath:/services
